### ISSUE TITLE
如何修改跨域请求的返回结果

### ISSUE THREAD

**Issue by vcxiaohan** [gzrichard/charles-share#1]
我的接口是【跨域】的，所以会先发送状态码为【204的OPTIONS】的请求，该次请求【不返回任何实体内容】，接下来才要发送真正的要请求实体内容的请求
而我在【Map Local】设置好了之后，它只会修改第一次的请求，根本就走不到发第二次请求的时机

**Comment by chen4342024** [comment]
我也碰到同样的问题，请求解决了么 ？

**Comment by vcxiaohan** [comment]
> 我也碰到同样的问题，请求解决了么 ？

没有解决，没有办法

**Comment by yibhou** [comment]
@vcxiaohan @chen4342024 可以用Rewrite功能设置一个Body规则，然后写个正则匹配响应并替换为你想要的请求数据就可以了
